# Generated by Django 4.2.11 on 2024-12-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_auth", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phonecode",
            options={
                "ordering": ("created_at",),
                "verbose_name": "СМС код аутентификации",
                "verbose_name_plural": "СМС коды аутентификации",
            },
        ),
        migrations.AlterModelOptions(
            name="smsmessage",
            options={
                "verbose_name": "Отправленное СМС",
                "verbose_name_plural": "Отправленные СМС",
            },
        ),
    ]
