# Generated by Django 4.2.11 on 2025-03-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
        ("order", "0001_initial"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingsession",
            name="stores",
            field=models.ManyToManyField(to="store.store"),
        ),
        migrations.AddField(
            model_name="shippingorder",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shipping.courier",
            ),
        ),
        migrations.AddField(
            model_name="shippingorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="order.order"
            ),
        ),
        migrations.AddField(
            model_name="shippingorder",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.store",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shipping.courier"
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="trips",
            field=models.ManyToManyField(to="shipping.trip"),
        ),
        migrations.AddField(
            model_name="couriershift",
            name="courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shipping.courier"
            ),
        ),
        migrations.AddField(
            model_name="couriershift",
            name="routes",
            field=models.ManyToManyField(to="shipping.route"),
        ),
    ]
