# Generated by Django 4.2.11 on 2025-03-19 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shipping", "0002_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="staff_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.staff"
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterIndexTogether(
            name="shippingorder",
            index_together={("pickup_time", "shipping_time")},
        ),
        migrations.AlterIndexTogether(
            name="route",
            index_together={("start_time", "end_time")},
        ),
        migrations.AlterUniqueTogether(
            name="couriershift",
            unique_together={("courier", "start_time")},
        ),
        migrations.AlterUniqueTogether(
            name="courier",
            unique_together={("user", "type")},
        ),
    ]
