# Generated by Django 4.2.11 on 2024-04-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="variant",
            field=models.CharField(blank=True, max_length=255, verbose_name="Variant"),
        ),
        migrations.AlterField(
            model_name="option",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price to sell.",
                max_digits=12,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("boolean", "True / False"),
                    ("float", "Float"),
                    ("date", "Date"),
                    ("select", "Select"),
                    ("radio", "Radio"),
                    ("multi_select", "Multi select"),
                    ("checkbox", "Checkbox"),
                    ("good", "Good"),
                ],
                default="text",
                max_length=255,
                verbose_name="Type",
            ),
        ),
    ]
