# Generated by Django 4.2.11 on 2024-08-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cooking_time",
            field=models.IntegerField(
                default=20,
                help_text="Приблизительное время, которое уйдет у повара на приготовление и сборку заказа на кухне. Указывается в минутах.",
                verbose_name="Время приготовления",
            ),
        ),
    ]
