# Generated by Django 4.2.11 on 2024-09-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productadditional",
            name="additional_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.additional",
                verbose_name="Дополнительный продукт",
            ),
        ),
    ]
