# Generated by Django 4.2.11 on 2024-06-26 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productclass",
            old_name="product_additionals",
            new_name="class_additionals",
        ),
        migrations.AlterUniqueTogether(
            name="productadditional",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productadditional",
            name="additional_product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_additional",
                to="catalogue.additional",
                verbose_name="Рекомендуемый продукт",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="productadditional",
            unique_together={
                ("primary_class", "primary_product", "additional_product")
            },
        ),
        migrations.RemoveField(
            model_name="productadditional",
            name="additional",
        ),
    ]
