# Generated by Django 4.2.11 on 2024-10-21 10:32

from django.db import migrations, models
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_alter_productadditional_additional_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="evotor_code",
            field=models.CharField(
                blank=True,
                max_length=128,
                verbose_name="Code Эвотор (По умолчанию = ID)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="evotor_id",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="ID Эвотор"
            ),
        ),
        migrations.AddField(
            model_name="productclass",
            name="measure_name",
            field=models.CharField(
                choices=[
                    ("", "Не задано"),
                    ("шт", "шт. - штуки"),
                    ("кг", "кг. - килограммы"),
                    ("л", "л. - литры"),
                    ("мл", "мл. - миллилитры"),
                    ("м", "м. - метры"),
                    ("компл", "компл. - комплекты"),
                    ("упак", "упак. - упаковки"),
                    ("ед", "ед. - единицы"),
                ],
                default="",
                max_length=128,
                verbose_name="Единицы изменения",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="upc",
            field=oscar.models.fields.NullCharField(
                help_text="Универсальный код продукта (Артикул) является идентификатором для продукта, который не является специфичным для конкретного товара. Например, ISBN книги",
                max_length=64,
                unique=True,
                verbose_name="Товарный код продукта UPC (Артикул)",
            ),
        ),
    ]
