# Generated by Django 4.2.11 on 2024-06-27 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalogue",
            "0002_rename_product_additionals_productclass_class_additionals_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Опция",
                "verbose_name_plural": "Опиции",
            },
        ),
        migrations.AlterField(
            model_name="option",
            name="required",
            field=models.BooleanField(
                default=False, verbose_name="Обязательная ли эта опция?"
            ),
        ),
        migrations.AlterField(
            model_name="productadditional",
            name="additional_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.additional",
                verbose_name="Рекомендуемый продукт",
            ),
        ),
        migrations.AlterField(
            model_name="productadditional",
            name="primary_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.productclass",
                verbose_name="Основной класс",
            ),
        ),
        migrations.AlterField(
            model_name="productadditional",
            name="primary_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.product",
                verbose_name="Основной продукт",
            ),
        ),
    ]
