# Generated by Django 4.2.11 on 2024-10-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_product_evotor_code_product_evotor_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productclass",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("full_access", "Полный доступ"),
                    ("read", "Просматривать товары и категории"),
                    ("change_stockrecord", "Изменять цену и наличие"),
                ),
                "verbose_name": "Класс товара",
                "verbose_name_plural": "Классы товара",
            },
        ),
    ]
