# Generated by Django 4.2.11 on 2024-08-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_alter_additional_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattribute",
            name="code",
            field=models.SlugField(max_length=128, unique=True, verbose_name="Код"),
        ),
    ]
