# Generated by Django 4.2.11 on 2024-08-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0005_alter_productattribute_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cooking_time",
            field=models.IntegerField(default=20, verbose_name="Время приготовления"),
        ),
    ]
