# Generated by Django 4.2.11 on 2024-08-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_product_cooking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(blank=True, max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="variant",
            field=models.CharField(blank=True, max_length=255, verbose_name="Вариант"),
        ),
        migrations.AlterField(
            model_name="productclass",
            name="class_additionals",
            field=models.ManyToManyField(
                blank=True,
                help_text="Дополнительные товары для всех продуктов этого класса",
                through="catalogue.ProductAdditional",
                to="catalogue.additional",
                verbose_name="Дополнительные товары класса",
            ),
        ),
        migrations.AlterField(
            model_name="productclass",
            name="options",
            field=models.ManyToManyField(
                blank=True, to="catalogue.option", verbose_name="Опция"
            ),
        ),
    ]
