# Generated by Django 4.2.11 on 2024-10-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_alter_productclass_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productclass",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("full_access", "Полный доступ к продуктам"),
                    ("read", "Просматривать товары и категории"),
                    ("update_stockrecord", "Изменять наличие товаров"),
                ),
                "verbose_name": "Класс товара",
                "verbose_name_plural": "Классы товара",
            },
        ),
    ]
