# Generated by Django 4.2.11 on 2024-08-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0007_alter_product_title_alter_product_variant_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="additional",
            old_name="img",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="productrecommendation",
            name="ranking",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=0,
                help_text="Определяет порядок товаров. Товар с более высоким значениемЗначение появится перед значением с более низким рейтингом.",
                verbose_name="Порядок",
            ),
        ),
    ]
