# Generated by Django 4.2.11 on 2024-11-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0007_alter_productclass_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="evotor_code",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Code Эвотор"
            ),
        ),
    ]
