# Generated by Django 4.2.11 on 2024-11-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_alter_product_evotor_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="evotor_id",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="ID Эвотор"
            ),
        ),
    ]
