# Generated by Django 4.2.11 on 2024-11-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0009_category_evotor_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productattribute",
            options={
                "ordering": ["attribute"],
                "verbose_name": "Атрибут продукта",
                "verbose_name_plural": "Атрибуты продукта",
            },
        ),
        migrations.AddField(
            model_name="productattribute",
            name="primary_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.productclass",
                verbose_name="Класс",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="primary_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Имя")),
                (
                    "code",
                    models.SlugField(max_length=128, unique=True, verbose_name="Код"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Текст"),
                            ("integer", "Целое число"),
                            ("boolean", "Да / Нет"),
                            ("float", "Дробное число"),
                            ("richtext", "Текстовое поле"),
                            ("option", "Опция"),
                            ("multi_option", "Мульти-опция"),
                            ("file", "Файл"),
                            ("image", "Изображение"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="Необходимый"),
                ),
                (
                    "option_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите группу параметров, если используете тип «Опция» или «Множество опций».",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_attributes",
                        to="catalogue.attributeoptiongroup",
                        verbose_name="Группа опций",
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибут",
                "verbose_name_plural": "Атрибуты",
                "ordering": ["code"],
                "abstract": False,
            },
        ),
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalogue.attribute",
                verbose_name="Атрибуты",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together={("attribute", "primary_product", "primary_class")},
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="code",
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="name",
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="option_group",
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="product_class",
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="required",
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="type",
        ),
    ]
