# Generated by Django 4.2.11 on 2024-11-12 04:43

from django.db import migrations, models
import django.db.models.deletion
import oscar.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("catalogue", "0010_alter_productattribute_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attributeoptiongroup",
            options={
                "verbose_name": "Группа атрибутов",
                "verbose_name_plural": "Группы атрибутов",
            },
        ),
        migrations.AlterModelOptions(
            name="productattribute",
            options={
                "verbose_name": "Значение атрибута продукта",
                "verbose_name_plural": "Значения атрибутов продукта",
            },
        ),
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="entity_content_type",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="entity_object_id",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_values",
                to="catalogue.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="product_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_values",
                to="catalogue.productclass",
                verbose_name="Класс продукта",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_boolean",
            field=models.BooleanField(
                blank=True, db_index=True, null=True, verbose_name="Логическое значение"
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=oscar.utils.models.get_image_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_float",
            field=models.FloatField(
                blank=True, db_index=True, null=True, verbose_name="Дробное число"
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=oscar.utils.models.get_image_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_integer",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="Целое число"
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_multi_option",
            field=models.ManyToManyField(
                blank=True,
                related_name="multi_valued_attribute_values",
                to="catalogue.attributeoption",
                verbose_name="Значение нескольких вариантов Мульти-Опции",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.attributeoption",
                verbose_name="Вариант значения Опции",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_richtext",
            field=models.TextField(
                blank=True, null=True, verbose_name="Текстовое поле"
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст"),
        ),
        migrations.AddField(
            model_name="productclass",
            name="class_attributes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Атрибуты для всех продуктов этого класса",
                through="catalogue.ProductAttribute",
                to="catalogue.attribute",
                verbose_name="Атрибуты класса",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="required",
            field=models.BooleanField(default=False, verbose_name="Обязательно"),
        ),
        migrations.AlterField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(
                help_text="Атрибут продукта — это то, что этот продукт можетиметь, например, размер, указанный его классом",
                through="catalogue.ProductAttribute",
                to="catalogue.attribute",
                verbose_name="Атрибуты",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="attribute",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.attribute",
                verbose_name="Атрибут",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together={("attribute", "product")},
        ),
        migrations.DeleteModel(
            name="ProductAttributeValue",
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="primary_class",
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="primary_product",
        ),
    ]
