# Generated by Django 4.2.11 on 2024-11-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0013_alter_productattribute_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["path", "order"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="productadditional",
            options={
                "ordering": ["primary_product", "-ranking"],
                "verbose_name": "Дополнительный товар",
                "verbose_name_plural": "Дополнительные товары",
            },
        ),
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together={("attribute", "product")},
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_promo",
        ),
        migrations.AlterField(
            model_name="attribute",
            name="option_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите группу параметров, если используете тип «Атрибут группы» или «Множество атрибутов группы».",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_attributes",
                to="catalogue.attributeoptiongroup",
                verbose_name="Группа атрибутов",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="required",
            field=models.BooleanField(
                default=False, verbose_name="Обязательный атрибут"
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Текст"),
                    ("integer", "Целое число"),
                    ("boolean", "Да / Нет"),
                    ("float", "Дробное число"),
                    ("richtext", "Текстовое поле"),
                    ("file", "Файл"),
                    ("image", "Изображение"),
                    ("option", "Один атрибут из группы"),
                    ("multi_option", "Множество атрибутов из группы"),
                ],
                default="text",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="attributes",
            field=models.ManyToManyField(
                help_text="Атрибут продукта — это то, что этот продукт можетиметь, например, размер, указанный его классом или в самом продукте",
                through="catalogue.ProductAttribute",
                to="catalogue.attribute",
                verbose_name="Атрибуты",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="value_multi_option",
            field=models.ManyToManyField(
                blank=True,
                related_name="multi_valued_attribute_values",
                to="catalogue.attributeoption",
                verbose_name="Значения группы атрибутов",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="value_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.attributeoption",
                verbose_name="Одно значение из группы атрибутов",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productadditional",
            unique_together={("primary_product", "additional_product")},
        ),
    ]
