# Generated by Django 4.2.11 on 2024-11-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0014_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="evotor_code",
        ),
    ]
