# Generated by Django 4.2.11 on 2024-11-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0015_remove_product_evotor_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="evotor_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="ID Эвотор"
            ),
        ),
    ]
