# Generated by Django 4.2.11 on 2024-11-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0016_alter_category_evotor_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attributeoption",
            name="code",
        ),
        migrations.RemoveField(
            model_name="attributeoptiongroup",
            name="code",
        ),
        migrations.AddField(
            model_name="attributeoption",
            name="evotor_id",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                unique=True,
                verbose_name="ID Эвотор",
            ),
        ),
        migrations.AddField(
            model_name="attributeoptiongroup",
            name="evotor_id",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                unique=True,
                verbose_name="ID Эвотор",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Определяет порядок отображения в списке. (Чем меньше, тем выше в списке)",
                verbose_name="Порядок",
            ),
        ),
    ]
