# Generated by Django 4.2.11 on 2024-11-26 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_store_options_alter_storeaddress_options_and_more"),
        ("basket", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="baskets",
                to="store.store",
                verbose_name="Магазин",
            ),
        ),
    ]
