# Generated by Django 4.2.11 on 2024-08-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.SmallIntegerField(
                        choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)],
                        verbose_name="Оценка",
                    ),
                ),
                ("body", models.TextField(verbose_name="Текст отзыва")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Отзыв заказа",
                "verbose_name_plural": "Отзывы заказов",
                "db_table": "order_review",
                "abstract": False,
            },
        ),
    ]
