# Generated by Django 4.2.11 on 2024-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderreview",
            name="is_open",
            field=models.BooleanField(default=False, verbose_name="Отзыв просмотрен"),
        ),
    ]
