# Generated by Django 4.2.11 on 2024-09-03 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="partners",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователи",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockrecord",
            unique_together={("partner", "partner_sku")},
        ),
    ]
