# Generated by Django 4.2.11 on 2024-09-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, verbose_name="Название"
            ),
        ),
    ]
