# Generated by Django 4.2.11 on 2024-08-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0002_partneraddress_coords_lat_partneraddress_coords_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockalert",
            name="status",
            field=models.CharField(
                choices=[("Открыто", "Открыто"), ("Закрыто", "Закрыто")],
                default="Открыто",
                max_length=128,
                verbose_name="Статус",
            ),
        ),
    ]
