# Generated by Django 4.2.11 on 2024-09-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="is_public",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Продукт доступен к покупке",
                verbose_name="Доступен",
            ),
        ),
    ]
