# Generated by Django 4.2.11 on 2024-10-21 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0004_partner_evotor_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Штрих-код"
                    ),
                ),
            ],
            options={
                "verbose_name": "Штрих-код",
                "verbose_name_plural": "Штрих-коды",
                "ordering": ("code",),
                "permissions": (("dashboard_access", "Can access dashboard"),),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Terminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imei",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Код imei"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Серийный номер"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Название"
                    ),
                ),
                (
                    "evotor_id",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="ID Эвотор"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Дата изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Смарт терминал Эвотор",
                "verbose_name_plural": "Смарт терминалы Эвотор",
                "ordering": ("name", "serial_number"),
                "permissions": (("dashboard_access", "Can access dashboard"),),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="partner",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default="2024-09-12 06:41:29.684400",
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="partner",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="Дата изменения"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="end_worktime",
            field=models.TimeField(
                default=datetime.time(21, 0), verbose_name="Время окончания смены"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="start_worktime",
            field=models.TimeField(
                default=datetime.time(9, 0), verbose_name="Время начала смены"
            ),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Цена закупки продукта",
                max_digits=12,
                null=True,
                verbose_name="Цена закупки",
            ),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="tax",
            field=models.CharField(
                choices=[
                    ("NO_VAT", "Без НДС."),
                    ("VAT_0", "Основная ставка 0%"),
                    ("VAT_10", "Основная ставка 10%."),
                    ("VAT_10_110", "Расчётная ставка 10%."),
                    (
                        "VAT_18",
                        "Основная ставка 18%. С первого января 2019 года может указывать как на 18%, так и на 20% ставку.",
                    ),
                    (
                        "VAT_18_118",
                        "Расчётная ставка 18%. С первого января 2019 года может указывать как на 18%, так и на 20% ставку.",
                    ),
                ],
                default="NO_VAT",
                max_length=128,
                verbose_name="Налог в процентах",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="terminals",
            field=models.ManyToManyField(
                blank=True,
                related_name="terminals",
                to="partner.terminal",
                verbose_name="Терминал",
            ),
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="bar_codes",
            field=models.ManyToManyField(
                blank=True,
                related_name="bars",
                to="partner.barcode",
                verbose_name="Штрих-коды",
            ),
        ),
    ]
