# Generated by Django 4.2.11 on 2024-10-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0005_barcode_terminal_partner_date_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminal",
            name="coords_lat",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Координаты широта"
            ),
        ),
        migrations.AddField(
            model_name="terminal",
            name="coords_long",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Координаты долгота"
            ),
        ),
        migrations.AddField(
            model_name="terminal",
            name="device_model",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Модель терминала"
            ),
        ),
    ]
