# Generated by Django 4.2.11 on 2024-10-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0006_terminal_coords_lat_terminal_coords_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="terminals",
            field=models.ManyToManyField(
                blank=True,
                related_name="partners",
                to="partner.terminal",
                verbose_name="Терминал",
            ),
        ),
    ]
