# Generated by Django 4.2.11 on 2024-10-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0007_alter_partner_terminals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="evotor_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="ID Эвотор"
            ),
        ),
    ]
