# Generated by Django 4.2.11 on 2024-10-30 12:22

from django.db import migrations, models
import oscar.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0009_alter_barcode_options_alter_partner_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockrecord",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Граница малых запасов",
                null=True,
                verbose_name="Граница малых запасов",
            ),
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="num_allocated",
            field=models.IntegerField(
                blank=True,
                help_text="Заказано",
                null=True,
                verbose_name="Количество заказано",
            ),
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="num_in_stock",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="В наличии",
                null=True,
                verbose_name="Количество в наличии",
            ),
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="partner_sku",
            field=models.CharField(
                help_text="Эвотор ID",
                max_length=128,
                verbose_name="Артикул в точке продажи",
            ),
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="price_currency",
            field=models.CharField(
                default=oscar.core.utils.get_default_currency,
                help_text="Валюта. Рубли = RUB",
                max_length=12,
                verbose_name="Валюта",
            ),
        ),
    ]
