# Generated by Django 4.2.11 on 2024-11-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0010_alter_stockrecord_low_stock_threshold_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="terminal",
            old_name="device_model",
            new_name="model",
        ),
    ]
