# Generated by Django 4.2.11 on 2024-11-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0012_alter_terminal_imei"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Активена точка продажи или нет",
                verbose_name="Активен",
            ),
        ),
    ]
