# Generated by Django 4.2.11 on 2024-11-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_alter_product_evotor_code"),
        ("partner", "0013_partner_is_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockrecord",
            unique_together={("partner", "product")},
        ),
        migrations.AddField(
            model_name="stockrecord",
            name="evotor_id",
            field=models.CharField(
                blank=True,
                help_text="Эвотор ID",
                max_length=128,
                null=True,
                verbose_name="Эвотор ID",
            ),
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="partner_sku",
            field=models.CharField(
                help_text="Артикул",
                max_length=128,
                verbose_name="Артикул в точке продажи",
            ),
        ),
    ]
