# Generated by Django 4.2.11 on 2024-11-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0014_alter_stockrecord_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockrecord",
            name="evotor_id",
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="partner_sku",
            field=models.CharField(
                help_text="Эвотор код, для связи продукта и товарной записи",
                max_length=128,
                verbose_name="Эвотор Code",
            ),
        ),
    ]
