# Generated by Django 4.2.11 on 2024-09-03 09:51

from django.db import migrations, models
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    oscar.models.fields.autoslugfield.AutoSlugField(
                        allow_unicode=True,
                        blank=True,
                        editable=False,
                        max_length=128,
                        populate_from="title",
                        unique=True,
                        verbose_name="Ярлык",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="promocats")),
                ("title", models.CharField(max_length=128, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Мета заголовок",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Мета описание"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PROMO", "Промо-категория"),
                            ("RECOMEND", "Рекомендоданые товары"),
                            ("ACTION", "Акция на товары"),
                        ],
                        default="RECOMEND",
                        max_length=255,
                        verbose_name="Тип категории товаров",
                    ),
                ),
                (
                    "products_related",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Продукты которые стоит показать на странице акции",
                        to="catalogue.product",
                        verbose_name="Связаные продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промо товары",
                "verbose_name_plural": "Промо товары",
                "db_table": "actions_promocategory",
                "ordering": ["order", "title"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    oscar.models.fields.autoslugfield.AutoSlugField(
                        allow_unicode=True,
                        blank=True,
                        editable=False,
                        max_length=128,
                        populate_from="title",
                        unique=True,
                        verbose_name="Ярлык",
                    ),
                ),
                ("image", models.ImageField(upload_to="actions")),
                ("title", models.CharField(max_length=128, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Мета заголовок",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Мета описание"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "products_related",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Продукты которые стоит показать на странице акции",
                        to="catalogue.product",
                        verbose_name="Связаные продукты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция для слайдера",
                "verbose_name_plural": "Акции для слайдера",
                "db_table": "actions_action",
                "ordering": ["order", "title"],
                "abstract": False,
            },
        ),
    ]
