# Generated by Django 4.2.11 on 2024-08-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="action",
            old_name="img",
            new_name="image",
        ),
    ]
