# Generated by Django 4.2.11 on 2024-08-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_img_action_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promocategory",
            old_name="img",
            new_name="image",
        ),
    ]
