# Generated by Django 4.2.11 on 2024-06-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="line1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Улица, дом"
            ),
        ),
    ]
