# Generated by Django 4.2.11 on 2024-06-27 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_alter_option_options_alter_option_required_and_more"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineattribute",
            name="additional",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="line_additionals",
                to="catalogue.additional",
                verbose_name="Доп. товар",
            ),
        ),
    ]
