# Generated by Django 4.2.11 on 2024-04-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_order_billing_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="country",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="postcode",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="state",
        ),
        migrations.DeleteModel(
            name="BillingAddress",
        ),
    ]
