# Generated by Django 4.2.11 on 2024-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_open",
            field=models.BooleanField(default=False, verbose_name="Заказ просмотрен"),
        ),
    ]
