# Generated by Django 4.2.11 on 2024-08-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_is_open"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_code",
        ),
        migrations.AlterField(
            model_name="order",
            name="is_open",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Заказ просмотрен"
            ),
        ),
    ]
