# Generated by Django 4.2.11 on 2024-09-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_order_partner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="tax_code",
        ),
        migrations.RemoveField(
            model_name="lineprice",
            name="tax_code",
        ),
        migrations.RemoveField(
            model_name="surcharge",
            name="tax_code",
        ),
    ]
