# Generated by Django 4.2.11 on 2024-09-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_line_tax_code_lineprice_tax_code_surcharge_tax_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="site",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Источник заказа"
            ),
        ),
    ]
