# Generated by Django 4.2.11 on 2024-10-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_order_site"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="partner_line_reference",
        ),
    ]
