# Generated by Django 4.2.11 on 2024-10-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_alter_ordernote_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ordernote",
            options={
                "ordering": ["-date_updated"],
                "permissions": (
                    ("full_access", "Полный доступ"),
                    ("read", "Просматривать заказы"),
                    ("update_order", "Изменять состав заказа"),
                    ("update_order_status", "Изменять статус заказа"),
                    ("update_order_payment", "Изменять оплату заказа"),
                ),
                "verbose_name": "Примечание к заказу",
                "verbose_name_plural": "Примечания к заказам",
            },
        ),
    ]
