# Generated by Django 4.2.11 on 2024-10-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_alter_ordernote_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_online",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Заказ сделан онлайн"
            ),
        ),
    ]
