# Generated by Django 4.2.11 on 2024-11-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0012_order_is_online"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_online",
        ),
    ]
