# Generated by Django 4.2.11 on 2025-03-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0003_alter_telegrammessage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrammessage",
            name="type",
            field=models.CharField(
                choices=[
                    ("order", "Уведомление о заказе"),
                    ("offer", "Уведомление о персональном предложении"),
                    ("sell", "Уведомления о новом заказе"),
                    ("status", "Уведомление об изменении статуса заказа"),
                    ("stock", "Уведомление о товарной записи"),
                    ("technical", "Техническое уведомление"),
                    ("error", "Уведомление об ошибке"),
                    ("misc", "Без типа"),
                ],
                default="misc",
                max_length=128,
                verbose_name="Тип сообщения",
            ),
        ),
    ]
