# Generated by Django 4.2.11 on 2024-04-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0002_remove_partneraddress_country_and_more"),
        ("order", "0003_remove_shippingaddress_country_and_more"),
        ("shipping", "0002_remove_orderanditemcharges_countries_and_more"),
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraddress",
            name="country",
        ),
        migrations.RemoveField(
            model_name="useraddress",
            name="is_default_for_billing",
        ),
        migrations.RemoveField(
            model_name="useraddress",
            name="num_orders_as_billing_address",
        ),
        migrations.RemoveField(
            model_name="useraddress",
            name="postcode",
        ),
        migrations.RemoveField(
            model_name="useraddress",
            name="state",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
