# Generated by Django 4.2.11 on 2024-07-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="coords_lat",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Координаты широта"
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="coords_long",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Координаты долгота"
            ),
        ),
    ]
