# Generated by Django 4.2.11 on 2024-07-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_useraddress_coords_lat_useraddress_coords_long"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryZona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(verbose_name="Номер зоны доставки"),
                ),
                (
                    "description",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Квартира"
                    ),
                ),
                ("order_price", models.PositiveIntegerField(verbose_name="Улица, дом")),
                ("coords", models.CharField(max_length=255, verbose_name="Улица, дом")),
                (
                    "isAvailable",
                    models.BooleanField(
                        max_length=255,
                        verbose_name="Доступность в данный момент зоны доставки",
                    ),
                ),
                (
                    "isHide",
                    models.BooleanField(
                        max_length=255,
                        verbose_name="Доступность в данный момент зоны доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зона доставки",
                "verbose_name_plural": "Зоны доставки",
                "abstract": False,
            },
        ),
    ]
