# Generated by Django 4.2.11 on 2024-07-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_deliveryzona"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryzona",
            name="delivery_price",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Минимальная цена заказа"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deliveryzona",
            name="coords",
            field=models.CharField(max_length=255, verbose_name="Координаты"),
        ),
        migrations.AlterField(
            model_name="deliveryzona",
            name="description",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzona",
            name="isAvailable",
            field=models.BooleanField(max_length=255, verbose_name="Доставка доступна"),
        ),
        migrations.AlterField(
            model_name="deliveryzona",
            name="isHide",
            field=models.BooleanField(max_length=255, verbose_name="Убрать с карты"),
        ),
        migrations.AlterField(
            model_name="deliveryzona",
            name="order_price",
            field=models.PositiveIntegerField(verbose_name="Минимальная цена заказа"),
        ),
    ]
