# Generated by Django 4.2.11 on 2024-07-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0004_deliveryzona_delivery_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryzona",
            name="coords",
            field=models.CharField(
                help_text="Координаты в формате: 56.050371,92.888167|56.046661,92.890356",
                max_length=255,
                verbose_name="Координаты",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzona",
            name="delivery_price",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Стоимость доставки"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzona",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Описание"
            ),
        ),
    ]
