# Generated by Django 4.2.11 on 2024-07-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0005_alter_deliveryzona_coords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryzona",
            name="number",
            field=models.PositiveIntegerField(
                unique=True, verbose_name="Номер зоны доставки"
            ),
        ),
    ]
