# Generated by Django 4.2.11 on 2024-07-09 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0006_alter_deliveryzona_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeliveryZona",
        ),
    ]
