# Generated by Django 4.2.11 on 2024-06-10 05:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oscar.models.fields
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Percentage", "Скидка — это процент от стоимости товара."),
                            (
                                "Absolute",
                                "Скидка\xa0— фиксированная сумма от суммы корзины.",
                            ),
                            (
                                "Fixed",
                                "Скидка — это фиксированная сумма от стоимости товара.",
                            ),
                            (
                                "Multibuy",
                                "Скидка – это предоставление самого дешевого товара бесплатно.",
                            ),
                            (
                                "Fixed price",
                                "Приобретайте товары, соответствующие условию, по фиксированной цене.",
                            ),
                            (
                                "Shipping absolute",
                                "Скидка – это фиксированная сумма стоимости доставки.",
                            ),
                            (
                                "Shipping fixed price",
                                "Получите доставку по фиксированной цене",
                            ),
                            (
                                "Shipping percentage",
                                "Скидка представляет собой процент от стоимости доставки.",
                            ),
                        ],
                        max_length=128,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "value",
                    oscar.models.fields.PositiveDecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Значение",
                    ),
                ),
                (
                    "max_affected_items",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Установите это, чтобы скидка не расходовала все товары в пределах, находящихся в корзине.",
                        null=True,
                        verbose_name="Максимальное количество товаров для скидки",
                    ),
                ),
                (
                    "proxy_class",
                    oscar.models.fields.NullCharField(
                        default=None,
                        max_length=255,
                        verbose_name="Пользовательский класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выгода",
                "verbose_name_plural": "Выгоды",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Count",
                                "Зависит от количества товаров в корзине, находящихся в определенном состоянии.",
                            ),
                            (
                                "Value",
                                "Зависит от стоимости товаров в корзине, находящихся в определенном состоянии.",
                            ),
                            (
                                "Coverage",
                                "Должно содержать заданное количество ОТЛИЧНЫХ элементов из диапазона условий.",
                            ),
                        ],
                        max_length=128,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "value",
                    oscar.models.fields.PositiveDecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Значение",
                    ),
                ),
                (
                    "proxy_class",
                    oscar.models.fields.NullCharField(
                        default=None,
                        max_length=255,
                        verbose_name="Пользовательский класс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Условие",
                "verbose_name_plural": "Условия",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Range",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="Имя"),
                ),
                (
                    "slug",
                    oscar.models.fields.autoslugfield.AutoSlugField(
                        allow_unicode=True,
                        blank=True,
                        editable=False,
                        max_length=128,
                        populate_from="name",
                        unique=True,
                        verbose_name="Ярлык",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Общедоступные ассортименты имеют страницу для клиентов.",
                        verbose_name="Является ли общедоступным",
                    ),
                ),
                (
                    "includes_all_products",
                    models.BooleanField(
                        default=False, verbose_name="Включает все продукты?"
                    ),
                ),
                (
                    "proxy_class",
                    oscar.models.fields.NullCharField(
                        default=None,
                        max_length=255,
                        unique=True,
                        verbose_name="Пользовательский прокси-класс",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="classes",
                        to="catalogue.productclass",
                        verbose_name="Типы продуктов",
                    ),
                ),
                (
                    "excluded_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="excludes",
                        to="catalogue.product",
                        verbose_name="Исключенные продукты",
                    ),
                ),
                (
                    "included_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="includes",
                        to="catalogue.category",
                        verbose_name="Включенные категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ассортимент",
                "verbose_name_plural": "Ассортимент",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RangeProductFileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filepath",
                    models.CharField(max_length=255, verbose_name="Путь к файлу"),
                ),
                ("size", models.PositiveIntegerField(verbose_name="Размер")),
                (
                    "date_uploaded",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("included", "Included products upload"),
                            ("excluded", "Excluded products upload"),
                        ],
                        default="included",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Failed", "Failed"),
                            ("Processed", "Processed"),
                        ],
                        default="Pending",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Сообщение об ошибке"
                    ),
                ),
                (
                    "date_processed",
                    models.DateTimeField(null=True, verbose_name="Дата обработки"),
                ),
                (
                    "num_new_skus",
                    models.PositiveIntegerField(
                        null=True, verbose_name="Количество новых SKU"
                    ),
                ),
                (
                    "num_unknown_skus",
                    models.PositiveIntegerField(
                        null=True, verbose_name="Количество неизвестных SKU"
                    ),
                ),
                (
                    "num_duplicate_skus",
                    models.PositiveIntegerField(
                        null=True, verbose_name="Количество повторяющихся SKU"
                    ),
                ),
                (
                    "range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_uploads",
                        to="offer.range",
                        verbose_name="Ассортимент",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загружено пользователем",
                    ),
                ),
            ],
            options={
                "verbose_name": "Загруженный файл продукта ассортимента",
                "verbose_name_plural": "Загруженные файлы продуктов линейки",
                "ordering": ("-date_uploaded",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RangeProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.product",
                    ),
                ),
                (
                    "range",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="offer.range"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("range", "product")},
            },
        ),
        migrations.AddField(
            model_name="range",
            name="included_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="includes",
                through="offer.RangeProduct",
                to="catalogue.product",
                verbose_name="Включенные продукты",
            ),
        ),
        migrations.CreateModel(
            name="ConditionalOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Это отображается в корзине клиента",
                        max_length=128,
                        unique=True,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True, upload_to="Offers", verbose_name="Изображение"
                    ),
                ),
                (
                    "slug",
                    oscar.models.fields.autoslugfield.AutoSlugField(
                        allow_unicode=True,
                        blank=True,
                        editable=False,
                        max_length=128,
                        populate_from="name",
                        unique=True,
                        verbose_name="Ярлык",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Это отображается на странице просмотра предложений",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            (
                                "Общее",
                                "Общее предложение - доступно всем пользователям",
                            ),
                            (
                                "Промокод",
                                "Промокод — доступно только после ввода кода промокода",
                            ),
                            (
                                "Пользовательское",
                                "Пользовательское предложение - доступно определенным типам пользователей.",
                            ),
                            (
                                "Предложение сеанса",
                                "Предложение сеанса\xa0– временное предложение, доступное для пользователей на время сеанса",
                            ),
                        ],
                        default="Общее",
                        max_length=128,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "exclusive",
                    models.BooleanField(
                        default=True,
                        help_text="Эксклюзивные предложения не могут быть объединены на одни и те же товары",
                        verbose_name="Эксклюзивное предложение",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Open", max_length=64, verbose_name="Статус"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Предложения с наивысшим приоритетом применяются в первую очередь",
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Предложения активны с даты начала. Оставьте это поле пустым, если у предложения нет даты начала",
                        null=True,
                        verbose_name="Дата начала",
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Предложения активны до даты окончания. Оставьте это поле пустым, если у предложения нет срока действия.",
                        null=True,
                        verbose_name="Дата окончания",
                    ),
                ),
                (
                    "max_global_applications",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Сколько раз можно использовать это предложение, прежде чем оно станет недоступным",
                        null=True,
                        verbose_name="Максимальное количество глобальных применений",
                    ),
                ),
                (
                    "max_user_applications",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Сколько раз один пользователь может воспользоваться этим предложением",
                        null=True,
                        verbose_name="Максимальное количество применений пользователем",
                    ),
                ),
                (
                    "max_basket_applications",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Сколько раз это предложение можно применить к корзине (и заказу)",
                        null=True,
                        verbose_name="Максимальное количество применений в корзине",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Когда предложение дало большую скидку на заказычем этот порог, то предложение становится недоступным",
                        max_digits=12,
                        null=True,
                        verbose_name="Максимальная скидка",
                    ),
                ),
                (
                    "total_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Общая скидка",
                    ),
                ),
                (
                    "num_applications",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество применений"
                    ),
                ),
                (
                    "num_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество заказов"
                    ),
                ),
                (
                    "redirect_url",
                    oscar.models.fields.ExtendedURLField(
                        blank=True,
                        verbose_name="Перенаправление URL-адреса (необязательно)",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "benefit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="offer.benefit",
                        verbose_name="Выгода",
                    ),
                ),
                (
                    "combinations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Выберите другие неэксклюзивные предложения, с которыми можно объединить это предложение на те же товары.",
                        limit_choices_to={"exclusive": False},
                        related_name="in_combination",
                        to="offer.conditionaloffer",
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="offer.condition",
                        verbose_name="Условие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Условное предложение",
                "verbose_name_plural": "Условные предложения",
                "ordering": ["-priority", "pk"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="condition",
            name="range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="offer.range",
                verbose_name="Ассортимент",
            ),
        ),
        migrations.AddField(
            model_name="benefit",
            name="range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="offer.range",
                verbose_name="Ассортимент",
            ),
        ),
        migrations.CreateModel(
            name="AbsoluteDiscountBenefit",
            fields=[],
            options={
                "verbose_name": "Абсолютная скидка",
                "verbose_name_plural": "Абсолютнаые скидки",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("offer.benefit",),
        ),
        migrations.CreateModel(
            name="CountCondition",
            fields=[],
            options={
                "verbose_name": "Условие подсчета",
                "verbose_name_plural": "Условия подсчетов",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("offer.condition",),
        ),
        migrations.CreateModel(
            name="CoverageCondition",
            fields=[],
            options={
                "verbose_name": "Условие покрытия",
                "verbose_name_plural": "Условия покрытиий",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("offer.condition",),
        ),
        migrations.CreateModel(
            name="FixedPriceBenefit",
            fields=[],
            options={
                "verbose_name": "Фиксированная скидка",
                "verbose_name_plural": "Фиксированные скидки",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("offer.benefit",),
        ),
        migrations.CreateModel(
            name="MultibuyDiscountBenefit",
            fields=[],
            options={
                "verbose_name": "Скидка при покупке нескольких покупок",
                "verbose_name_plural": "Скидки при покупке нескольких покупок",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("offer.benefit",),
        ),
        migrations.CreateModel(
            name="PercentageDiscountBenefit",
            fields=[],
            options={
                "verbose_name": "Процентная скидка",
                "verbose_name_plural": "Процентные скидки",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("offer.benefit",),
        ),
        migrations.CreateModel(
            name="ShippingBenefit",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("offer.benefit",),
        ),
        migrations.CreateModel(
            name="ValueCondition",
            fields=[],
            options={
                "verbose_name": "Условие значения",
                "verbose_name_plural": "Условия значений",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("offer.condition",),
        ),
        migrations.CreateModel(
            name="FixedUnitDiscountBenefit",
            fields=[],
            options={
                "verbose_name": "Фиксированная скидка за единицу",
                "verbose_name_plural": "Фиксированные скидки за единицу",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("offer.absolutediscountbenefit",),
        ),
        migrations.CreateModel(
            name="ShippingAbsoluteDiscountBenefit",
            fields=[],
            options={
                "verbose_name": "Преимущество абсолютной скидки на доставку",
                "verbose_name_plural": "Преимущества абсолютной скидки на доставку",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("offer.shippingbenefit",),
        ),
        migrations.CreateModel(
            name="ShippingFixedPriceBenefit",
            fields=[],
            options={
                "verbose_name": "Фиксированная цена доставки",
                "verbose_name_plural": "Фиксированные цены доставки",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("offer.shippingbenefit",),
        ),
        migrations.CreateModel(
            name="ShippingPercentageDiscountBenefit",
            fields=[],
            options={
                "verbose_name": "Процентная скидка на доставку",
                "verbose_name_plural": "Процентнаые скидки на доставку",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("offer.shippingbenefit",),
        ),
    ]
