# Generated by Django 4.2.11 on 2024-08-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="range",
            name="includes_all_products",
            field=models.BooleanField(
                default=False,
                help_text="Включает все продукты выбраных категорий.",
                verbose_name="Все продукты?",
            ),
        ),
    ]
