# Generated by Django 4.2.11 on 2024-10-25 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benefit",
            options={
                "verbose_name": "Предложение скидки",
                "verbose_name_plural": "Предложения скидки",
            },
        ),
        migrations.AlterField(
            model_name="conditionaloffer",
            name="benefit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="offer.benefit",
                verbose_name="Предложение скидки",
            ),
        ),
    ]
