# Generated by Django 4.2.11 on 2024-08-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0002_alter_range_includes_all_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conditionaloffer",
            old_name="img",
            new_name="image",
        ),
    ]
