# Generated by Django 4.2.11 on 2025-03-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("new-order", "Уведомления о новых заказах"),
                            (
                                "status-order",
                                "Уведомления об изменении статусов заказов",
                            ),
                            ("stock", "Уведомления о товарных остатках"),
                            ("error", "Уведомления об ошибках"),
                            ("technical", "Технические уведомления"),
                        ],
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="staff",
            name="notif",
        ),
        migrations.AddField(
            model_name="staff",
            name="notifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="staffs",
                to="user.staffnotification",
                verbose_name="Уведомления",
            ),
        ),
    ]
