# Generated by Django 4.2.11 on 2025-03-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_staffnotification_remove_staff_notif_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staffnotification",
            options={
                "verbose_name": "Уведомление персонала",
                "verbose_name_plural": "Уведомления персонала",
            },
        ),
        migrations.AlterField(
            model_name="staffnotification",
            name="code",
            field=models.CharField(
                choices=[
                    ("order", "Уведомления о новых заказах"),
                    ("status", "Уведомления об изменении статусов заказов"),
                    ("stock", "Уведомления о товарных остатках"),
                    ("error", "Уведомления об ошибках"),
                    ("technical", "Технические уведомления"),
                ],
                max_length=128,
                unique=True,
            ),
        ),
        migrations.AlterModelTable(
            name="staffnotification",
            table="auth_staffnotification",
        ),
    ]
