# Generated by Django 4.2.11 on 2025-03-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_staffnotification_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="staffnotification",
            table="auth_notification",
        ),
    ]
