# Generated by Django 4.2.11 on 2025-03-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_staffnotification_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Настройка уведомлений",
                "verbose_name_plural": "Настройки уведомлений",
                "db_table": "auth_notificationsetting",
            },
        ),
        migrations.RemoveField(
            model_name="staff",
            name="notifications",
        ),
        migrations.RemoveField(
            model_name="user",
            name="notif",
        ),
        migrations.DeleteModel(
            name="StaffNotification",
        ),
        migrations.AddField(
            model_name="user",
            name="notification_settings",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="user.notificationsetting",
                verbose_name="Настройки уведомлений",
            ),
        ),
    ]
