# Generated by Django 4.2.11 on 2025-03-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_notificationsetting_remove_staff_notifications_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="telegram_id",
        ),
    ]
