# Generated by Django 4.2.11 on 2024-09-03 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partner", "0001_initial"),
        ("delivery", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverysession",
            name="partners",
            field=models.ManyToManyField(to="partner.partner"),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="delivery.courier",
            ),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="order.order"
            ),
        ),
        migrations.AddField(
            model_name="deliveryorder",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="partner.partner",
            ),
        ),
        migrations.AddField(
            model_name="couriershift",
            name="courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="delivery.courier"
            ),
        ),
        migrations.AddField(
            model_name="couriershift",
            name="routes",
            field=models.ManyToManyField(to="delivery.route"),
        ),
    ]
