# Generated by Django 4.2.11 on 2024-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryzona",
            name="coords",
            field=models.CharField(
                help_text="Координаты в формате: [[55.730719,37.583146],[55.719093,37.677903]] Получить можно на сайте: http://mapinit.ru/coords/",
                max_length=1020,
                verbose_name="Координаты",
            ),
        ),
    ]
