# Generated by Django 4.2.11 on 2024-08-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryzona",
            name="isAvailable",
            field=models.BooleanField(
                default=True, max_length=255, verbose_name="Доставка доступна"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzona",
            name="isHide",
            field=models.BooleanField(
                default=False, max_length=255, verbose_name="Убрать с карты"
            ),
        ),
    ]
