# Generated by Django 4.2.11 on 2024-09-23 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_staff_remove_profile_user_user_notif_and_more"),
        ("delivery", "0002_alter_deliveryzona_order_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courier",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.staff"
            ),
        ),
    ]
