# Generated by Django 4.2.11 on 2024-12-13 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wishlists", "0002_remove_line_title_line_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="line",
            options={
                "ordering": ["pk"],
                "verbose_name": "Позиция избранного",
                "verbose_name_plural": "Позиции избранного",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={
                "ordering": ("owner", "date_created"),
                "verbose_name": "Избранное",
                "verbose_name_plural": "Списки избранного",
            },
        ),
    ]
