# Generated by Django 4.2.11 on 2024-03-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0006_auto_20200724_0909"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockrecord",
            name="old_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Old price.",
                max_digits=12,
                null=True,
                verbose_name="Old Price",
            ),
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price to sell.",
                max_digits=12,
                null=True,
                verbose_name="Price",
            ),
        ),
    ]
