# Generated by Django 4.2.11 on 2024-08-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": [
                    "username",
                    "email",
                    "password",
                    "name",
                    "is_staff",
                    "staff",
                    "is_active",
                    "is_email_verified",
                    "date_joined",
                    "last_login",
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="user",
            name="staff",
            field=models.CharField(
                blank=True, max_length=127, verbose_name="Должность"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
