# Generated by Django 4.2.11 on 2024-08-26 07:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Формат телефона: '+79950750075",
                max_length=11,
                region=None,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
