# Generated by Django 4.2.11 on 2024-09-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Телеграм ID"
            ),
        ),
    ]
