# Generated by Django 4.2.11 on 2024-08-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_user_name_user_staff_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="img",
            new_name="image",
        ),
    ]
