# Generated by Django 4.2.11 on 2024-06-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_alter_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="img",
            field=models.ImageField(blank=True, upload_to="profile"),
        ),
    ]
