# Generated by Django 4.2.11 on 2024-09-23 08:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_telegram_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Отчество"
                    ),
                ),
                ("job", models.CharField(max_length=127, verbose_name="Должность")),
                (
                    "gender",
                    models.CharField(
                        choices=[("М", "Мужчина"), ("Ж", "Женщина")],
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Возраст"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile", verbose_name="Фото"
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(max_length=128, verbose_name="ID Телеграм чата"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Активен сотрудник или нет",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "notif",
                    models.CharField(
                        choices=[
                            ("new-order", " Только уведомления о новых заказах"),
                            (
                                "status-order",
                                "Уведомления об изменении заказов и новых заказах",
                            ),
                            ("technical", "Технические уведомления"),
                            ("off", "Отключить уведомления"),
                        ],
                        default="new-order",
                        max_length=128,
                        verbose_name="Уведомления",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="notif",
            field=models.CharField(
                choices=[
                    ("order", "Только уведомления о заказах"),
                    ("offer", "Уведомления об персональных акциях и предложениях"),
                    ("off", "Отключить уведомления"),
                ],
                default="order",
                max_length=128,
                verbose_name="Уведомления",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Активен пользователь или нет",
                verbose_name="Активен",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Повар, Курьер, Менеджер и т.д.",
                verbose_name="Это сотрудник?",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="Телеграм ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True,
                help_text="Формат телефона: '+7 (900) 000-0000",
                max_length=12,
                region=None,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
