# Generated by Django 4.2.11 on 2024-09-03 05:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_first_name_remove_user_last_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": [
                    "username",
                    "email",
                    "password",
                    "name",
                    "is_staff",
                    "is_active",
                    "is_email_verified",
                    "date_joined",
                    "last_login",
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="staff",
        ),
        migrations.AddField(
            model_name="profile",
            name="job",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Менеджер", "Менеджер"),
                    ("Курьер", "Курьер"),
                    ("Сотрудник кухни", "Сотрудник кухни"),
                ],
                max_length=127,
                verbose_name="Должность",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.PositiveIntegerField(blank=True, verbose_name="Age"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Повар, Курьер, Менеджер и т.д.",
                verbose_name="Это сотрудник?",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="Формат телефона: '+7 (900) 000-0000",
                max_length=12,
                region=None,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
