# Generated by Django 4.2.11 on 2024-09-23 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_alter_courier_profile"),
        ("user", "0003_staff_remove_profile_user_user_notif_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
