# Generated by Django 4.2.11 on 2024-09-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_delete_profile_staff_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={"verbose_name": "Персонал", "verbose_name_plural": "Персонал"},
        ),
        migrations.AlterField(
            model_name="staff",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Возраст"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="staff",
            name="job",
            field=models.CharField(
                db_index=True, max_length=127, verbose_name="Должность"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="middle_name",
            field=models.CharField(
                blank=True, default=1, max_length=255, verbose_name="Отчество"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="staff",
            name="notif",
            field=models.CharField(
                choices=[
                    ("new-order", " Только уведомления о новых заказах"),
                    (
                        "status-order",
                        "Уведомления об изменении заказов и новых заказах",
                    ),
                    ("technical", "Технические уведомления"),
                    ("off", "Отключить уведомления"),
                ],
                db_index=True,
                default="new-order",
                max_length=128,
                verbose_name="Уведомления",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="notif",
            field=models.CharField(
                choices=[
                    ("order", "Только уведомления о заказах"),
                    ("offer", "Уведомления об персональных акциях и предложениях"),
                    ("off", "Отключить уведомления"),
                ],
                db_index=True,
                default="order",
                max_length=128,
                verbose_name="Уведомления",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Телеграм ID"
            ),
        ),
        migrations.AlterModelTable(
            name="staff",
            table="auth_staff",
        ),
    ]
