# Generated by Django 4.2.11 on 2024-09-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_options_remove_user_staff_profile_job_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default=24, max_length=255, verbose_name="Имя"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default=1, max_length=255, verbose_name="Фамилия"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Отчество"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Возраст"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("М", "Мужчина"), ("Ж", "Женщина")],
                max_length=1,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="job",
            field=models.CharField(
                choices=[
                    ("Менеджер", "Менеджер"),
                    ("Курьер", "Курьер"),
                    ("Сотрудник кухни", "Сотрудник кухни"),
                ],
                max_length=127,
                verbose_name="Должность",
            ),
        ),
    ]
