# Generated by Django 4.2.11 on 2024-09-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_staff_options_alter_staff_age_alter_staff_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="notif",
            field=models.CharField(
                choices=[
                    ("new-order", "Только уведомления о новых заказах"),
                    (
                        "status-order",
                        "Уведомления об изменении заказов и новых заказах",
                    ),
                    ("technical", "Технические уведомления"),
                    ("off", "Отключить уведомления"),
                ],
                db_index=True,
                default="new-order",
                max_length=128,
                verbose_name="Уведомления",
            ),
        ),
    ]
