# Generated by Django 4.2.11 on 2024-10-22 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0013_groupevotor"),
        ("user", "0006_alter_staff_notif"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="job",
        ),
        migrations.AddField(
            model_name="staff",
            name="evotor_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="ID Телеграм чата"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staffs",
                to="auth.group",
                verbose_name="Должность",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="telegram_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="ID Телеграм чата"
            ),
        ),
    ]
