# Generated by Django 4.2.11 on 2024-10-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_staff_job_staff_evotor_id_staff_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Возраст"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("М", "Мужчина"), ("Ж", "Женщина")],
                max_length=1,
                null=True,
                verbose_name="Пол",
            ),
        ),
    ]
