# Generated by Django 4.2.11 on 2024-10-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_staff_age_alter_staff_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={
                "permissions": (("full_access", "Полный доступ ко всему сайту"),),
                "verbose_name": "Персонал",
                "verbose_name_plural": "Персонал",
            },
        ),
    ]
