# Generated by Django 4.2.11 on 2024-10-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_staff_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="image",
        ),
    ]
