# Generated by Django 4.2.11 on 2024-10-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_staff_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="evotor_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="ID Эвотор"
            ),
        ),
    ]
