# Generated by Django 4.2.11 on 2024-11-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_staff_evotor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="first_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Отчество"
            ),
        ),
    ]
