# Generated by Django 4.2.11 on 2024-11-02 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_staff_first_name_alter_staff_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
