# Generated by Django 4.2.11 on 2024-04-01 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0028_abstractadditional_alter_productattribute_code_and_more"),
        ("order", "0015_orderlinediscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineattribute",
            name="additional",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="line_attributes",
                to="catalogue.additional",
                verbose_name="Additional",
            ),
        ),
    ]
