# Generated by Django 4.2.11 on 2025-02-28 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        ("action", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocategoryproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogue.product"
            ),
        ),
        migrations.AddField(
            model_name="promocategoryproduct",
            name="promo_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="action.promocategory"
            ),
        ),
        migrations.AddField(
            model_name="promocategory",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Товары которые будут показаны в продвигаемой категории.",
                related_name="promo_categories",
                through="action.PromoCategoryProduct",
                to="catalogue.product",
                verbose_name="Связаные товары",
            ),
        ),
        migrations.AddField(
            model_name="actionproduct",
            name="action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="action.action"
            ),
        ),
        migrations.AddField(
            model_name="actionproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogue.product"
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Товары которые будут показаны на странице акции.",
                related_name="actions",
                through="action.ActionProduct",
                to="catalogue.product",
                verbose_name="Связаные товары",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promocategoryproduct",
            unique_together={("promo_category", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="actionproduct",
            unique_together={("action", "product")},
        ),
    ]
