# Generated by Django 4.2.11 on 2024-10-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={
                "ordering": ["pk"],
                "verbose_name": "Источник оплаты",
                "verbose_name_plural": "Источники оплаты",
            },
        ),
    ]
