# Generated by Django 4.2.11 on 2024-10-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_source_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={
                "ordering": ["pk"],
                "permissions": (
                    ("full_access", "Полный доступ"),
                    ("read", "Просматривать платежи и возвраты"),
                    ("make_refund", "Остуществлять возвраты"),
                ),
                "verbose_name": "Источник оплаты",
                "verbose_name_plural": "Источники оплаты",
            },
        ),
    ]
