# Generated by Django 4.2.11 on 2024-11-05 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0013_partner_is_active"),
        ("order", "0012_order_is_online"),
        ("payment", "0005_alter_source_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=255)),
                ("field_value", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Дополнительное поле чека СRM",
                "verbose_name_plural": "Дополнительные поля чека СRM",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("SELL", "Продажа"), ("PAYBACK", "Возврат")],
                        max_length=50,
                    ),
                ),
                ("evotor_id", models.CharField(max_length=255)),
                ("device_id", models.CharField(max_length=255)),
                ("shift_id", models.CharField(max_length=255)),
                ("employee_id", models.CharField(max_length=255)),
                ("info_check", models.BooleanField()),
                ("egais", models.BooleanField()),
                (
                    "total_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_time", models.DateTimeField(verbose_name="Дата чека")),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "extras",
                    models.ManyToManyField(
                        related_name="receipts", to="payment.receiptextra"
                    ),
                ),
                (
                    "lines",
                    models.ManyToManyField(related_name="receipts", to="order.line"),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="partner.partner",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="payment.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чек СRM",
                "verbose_name_plural": "Чеки СRM",
                "ordering": ("-date_created",),
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="payment.receipt",
                verbose_name="Чек",
            ),
        ),
    ]
