# Generated by Django 4.2.11 on 2024-11-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_receiptextra_receipt_alter_transaction_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="receipt",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Чек"
            ),
        ),
    ]
