# Generated by Django 4.2.11 on 2024-11-05 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0007_alter_transaction_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="receipt",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="payment.receipt",
                verbose_name="Чек",
            ),
            preserve_default=False,
        ),
    ]
