# Generated by Django 4.2.11 on 2024-11-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_alter_transaction_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="receipt",
            field=models.BooleanField(blank=True, default=False, verbose_name="Чек"),
        ),
        migrations.DeleteModel(
            name="Receipt",
        ),
        migrations.DeleteModel(
            name="ReceiptExtra",
        ),
    ]
