# Generated by Django 4.2.11 on 2024-11-26 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_store_options_alter_storeaddress_options_and_more"),
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="line",
            name="evotor_code",
            field=models.CharField(max_length=128, verbose_name="Артикул в магазине"),
        ),
        migrations.AlterField(
            model_name="line",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_lines",
                to="store.store",
                verbose_name="Магазин",
            ),
        ),
        migrations.AlterField(
            model_name="line",
            name="store_line_notes",
            field=models.TextField(blank=True, verbose_name="Примечание магазина"),
        ),
        migrations.AlterField(
            model_name="line",
            name="store_name",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Название магазина"
            ),
        ),
    ]
