# Generated by Django 4.2.11 on 2024-11-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_line_evotor_code_alter_line_store_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="upc",
        ),
        migrations.AddField(
            model_name="line",
            name="article",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Артикул товара"
            ),
        ),
    ]
