# Generated by Django 4.2.11 on 2024-11-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_line_upc_line_article"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="title",
        ),
        migrations.AddField(
            model_name="line",
            name="name",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Название товара"
            ),
            preserve_default=False,
        ),
    ]
