# Generated by Django 4.2.11 on 2024-12-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_remove_line_title_line_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="evotor_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="ID Эвотор"
            ),
        ),
        migrations.AlterField(
            model_name="orderdiscount",
            name="frequency",
            field=models.PositiveIntegerField(
                null=True, verbose_name="Количество применений"
            ),
        ),
        migrations.AlterField(
            model_name="orderdiscount",
            name="voucher_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID Промокода"
            ),
        ),
    ]
