# Generated by Django 4.2.11 on 2024-12-04 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_stockrecord_is_public"),
        ("order", "0006_order_evotor_id_alter_orderdiscount_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="store.store",
                verbose_name="Магазин",
            ),
        ),
    ]
