# Generated by Django 4.2.11 on 2024-12-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_order_store"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderlinediscount",
            options={
                "ordering": ["pk"],
                "verbose_name": "Скидка на позицию заказа",
                "verbose_name_plural": "Скидки на позиции заказов",
            },
        ),
        migrations.AlterField(
            model_name="orderlinediscount",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Скидка на позицию заказа",
            ),
        ),
    ]
