# Generated by Django 4.2.11 on 2024-11-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CRMEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("TERMINAL", "Терминал"),
                            ("STORE", "Точка продажи"),
                            ("RECEIPT", "Чек"),
                            ("DOC", "Документы"),
                            ("INSTALLATION", "Установка / Удаление"),
                            ("STAFF", "Персонал"),
                            ("PRODUCT", "товары"),
                            ("MICS", "Неизвестно"),
                        ],
                        default="MICS",
                        max_length=32,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CREATION", "Создание"),
                            ("DELETE", "Удаление"),
                            ("UPDATE", "Обновление"),
                            ("INFO", "Инфо"),
                        ],
                        default="INFO",
                        max_length=255,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие СRM",
                "verbose_name_plural": "События СRM",
                "ordering": ("-date_created",),
            },
        ),
    ]
