# Generated by Django 4.2.11 on 2024-10-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("TERMINAL", "Терминал"),
                            ("PARTNER", "Точка продажи"),
                            ("RECEIPT", "Чек"),
                            ("DOC", "Документы"),
                            ("INSTALLATION", "Установка / Удаление"),
                            ("STAFF", "Персонал"),
                            ("PRODUCT", "Продукты"),
                            ("MICS", "Неизвестно"),
                        ],
                        default="MICS",
                        max_length=32,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CREATION", "Создание"),
                            ("DELETE", "Удаление"),
                            ("UPDATE", "Обновление"),
                            ("INFO", "Инфо"),
                        ],
                        default="INFO",
                        max_length=255,
                    ),
                ),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Событие СRM",
                "verbose_name_plural": "События СRM",
                "ordering": ("-date_sent",),
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="CRMToken",
        ),
        migrations.DeleteModel(
            name="CRMUser",
        ),
    ]
