# Generated by Django 4.2.11 on 2024-10-21 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_crmevent_delete_crmtoken_delete_crmuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crmevent",
            options={
                "ordering": ("-date_created",),
                "verbose_name": "Событие СRM",
                "verbose_name_plural": "События СRM",
            },
        ),
        migrations.RemoveField(
            model_name="crmevent",
            name="date_sent",
        ),
        migrations.AddField(
            model_name="crmevent",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
