# Generated by Django 4.2.11 on 2024-12-18 13:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderAndItemCharges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    oscar.models.fields.autoslugfield.AutoSlugField(
                        allow_unicode=True,
                        blank=True,
                        editable=False,
                        max_length=128,
                        overwrite=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="Ярлык",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=128, unique=True, verbose_name="Имя"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price_per_order",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Цена за заказ",
                    ),
                ),
                (
                    "price_per_item",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Цена за товар",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Бесплатная доставка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата заказа и товара",
                "verbose_name_plural": "Оплаты заказов и товаров",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WeightBased",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    oscar.models.fields.autoslugfield.AutoSlugField(
                        allow_unicode=True,
                        blank=True,
                        editable=False,
                        max_length=128,
                        overwrite=True,
                        populate_from="name",
                        unique=True,
                        verbose_name="Ярлык",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=128, unique=True, verbose_name="Имя"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "default_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Вес товара по умолчанию в кг, если атрибут веса не определен",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Вес по умолчанию",
                    ),
                ),
            ],
            options={
                "verbose_name": "Метод доставки по весу",
                "verbose_name_plural": "Методы доставки по весу",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WeightBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upper_limit",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=3,
                        help_text="Введите верхний предел этой весовой категории в кг. Нижний предел будет определяться другими весовыми категориями",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Верхний предел",
                    ),
                ),
                (
                    "charge",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Плата",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bands",
                        to="shipping.weightbased",
                        verbose_name="Метод",
                    ),
                ),
            ],
            options={
                "verbose_name": "Весовой диапазон",
                "verbose_name_plural": "Весовые диапазоны",
                "ordering": ["method", "upper_limit"],
            },
        ),
    ]
