# Generated by Django 4.2.11 on 2025-03-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=255, verbose_name='Поддомен клиента')),
                ('auth', models.CharField(choices=[('apps.user.auth_backends.PhoneBackend', 'Телефон'), ('apps.user.auth_backends.PhoneBackend', 'Электронная почта')], default='apps.user.auth_backends.PhoneBackend', max_length=255, verbose_name='Аунтификация')),
                ('sms_provider', models.CharField(blank=True, help_text='Имя с которого будует отсылаться СМС', max_length=255, null=True, verbose_name='СМС имя провайдера')),
                ('sms_debug', models.BooleanField(default=False, help_text='Если значение положительное, то смс не высылаются. Для входа на сайт подходит код: 1111', max_length=255, verbose_name='Тестирование СМС')),
                ('sms_auth_login', models.CharField(blank=True, help_text='Электронная почта аккаунта SMSAERO', max_length=255, null=True, verbose_name='SMSAERO логин')),
                ('sms_auth_token', models.CharField(blank=True, help_text='Ключ полученый при регистрации', max_length=255, null=True, verbose_name='SMSAERO API токен')),
                ('yoomoney_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID аккаунта ЮКасса')),
                ('yoomoney_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Секретный ключ аккаунта ЮКасса')),
                ('tax_system', models.CharField(blank=True, choices=[(0, 'Общая система налогообложения'), (1, 'Упрощенная (УСН, доходы)'), (2, 'Упрощенная (УСН, доходы минус расходы)'), (3, 'Единый налог на вмененный доход (ЕНВД)'), (4, 'Единый сельскохозяйственный налог (ЕСН)'), (5, 'Патентная система налогообложения')], default=0, max_length=1, null=True, verbose_name='Система налогообложения')),
                ('shipping_available', models.BooleanField(default=False, help_text='Магазин осуществляет доставку?', verbose_name='Доставка')),
                ('shipping_provider', models.CharField(blank=True, help_text='API ключ Яндекс, 2ГИС или DaData', max_length=255, null=True, verbose_name='Ключ API карт')),
                ('shipping_api_key', models.CharField(blank=True, help_text='API ключ Яндекс, 2ГИС или DaData', max_length=255, null=True, verbose_name='Ключ API карт')),
                ('store_select', models.BooleanField(default=False, help_text='Если значение положительное, то клиентам доступен выбор магазина, и корзина может содержать товары одновременно только из одного выбранного магазина', verbose_name='Несколько магазинов')),
                ('support_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на канал поддержки')),
                ('analytics_google', models.CharField(max_length=255, null=True, verbose_name='ID Google аналитики')),
                ('analytics_yandex', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Яндекс аналитики')),
                ('payments', models.ManyToManyField(blank=True, related_name='settings', to='settings.paymentsettings', verbose_name='Способы оплаты')),
                ('store_default', models.ForeignKey(blank=True, help_text='Данный магазин используется, если клиент еще не выбрал магазин', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store', verbose_name='Основной магазин')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
