# Generated by Django 4.2.11 on 2024-04-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderanditemcharges",
            name="countries",
        ),
        migrations.RemoveField(
            model_name="weightbased",
            name="countries",
        ),
    ]
