# Generated by Django 4.2.11 on 2025-03-20 09:42

import apps.sms.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Cost')),
            ],
            options={
                'verbose_name': 'Отправленное СМС',
                'verbose_name_plural': 'Отправленные СМС',
            },
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('code', models.PositiveIntegerField(default=apps.sms.utils.random_code)),
                ('valid_to', models.DateTimeField(default=apps.sms.utils.valid_to)),
                ('resend_at', models.DateTimeField(default=apps.sms.utils.resend_at)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'СМС код аутентификации',
                'verbose_name_plural': 'СМС коды аутентификации',
                'ordering': ('created_at',),
            },
        ),
    ]
