# Generated by Django 4.2.11 on 2024-12-18 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rangeproductfileupload",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Загружено пользователем",
            ),
        ),
        migrations.AddField(
            model_name="rangeproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalogue.product"
            ),
        ),
        migrations.AddField(
            model_name="rangeproduct",
            name="range",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="offer.range"
            ),
        ),
        migrations.AddField(
            model_name="range",
            name="classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="classes",
                to="catalogue.productclass",
                verbose_name="Типы товаров",
            ),
        ),
        migrations.AddField(
            model_name="range",
            name="excluded_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="excludes",
                to="catalogue.product",
                verbose_name="Исключенные товары",
            ),
        ),
        migrations.AddField(
            model_name="range",
            name="included_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="includes",
                to="catalogue.category",
                verbose_name="Включенные категории",
            ),
        ),
        migrations.AddField(
            model_name="range",
            name="included_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="includes",
                through="offer.RangeProduct",
                to="catalogue.product",
                verbose_name="Включенные товары",
            ),
        ),
        migrations.AddField(
            model_name="conditionaloffer",
            name="combinations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите другие неэксклюзивные предложения, с которыми можно объединить это предложение на те же товары.",
                limit_choices_to={"exclusive": False},
                related_name="in_combination",
                to="offer.conditionaloffer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rangeproduct",
            unique_together={("range", "product")},
        ),
        migrations.AddField(
            model_name="conditionaloffer",
            name="benefit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="offer.benefit",
                verbose_name="Предложение скидки",
            ),
        ),
        migrations.AddField(
            model_name="conditionaloffer",
            name="condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="offer.condition",
                verbose_name="Условие",
            ),
        ),
        migrations.AddField(
            model_name="condition",
            name="range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="offer.range",
                verbose_name="Ассортимент",
            ),
        ),
        migrations.AddField(
            model_name="benefit",
            name="range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="offer.range",
                verbose_name="Ассортимент",
            ),
        ),
    ]
