# Generated by Django 4.2.11 on 2024-12-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conditionaloffer",
            name="max_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Когда сумма всех скидок предложения достигнет этого значения,то предложение становится недоступным",
                max_digits=12,
                null=True,
                verbose_name="Максимальная скидка",
            ),
        ),
    ]
