# Generated by Django 4.2.11 on 2025-03-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evotor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evotorevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATION", "Создание"),
                    ("DELETE", "Удаление"),
                    ("UPDATE", "Обновление"),
                    ("INFO", "Инфо"),
                    ("BULK", "Переодическая задача"),
                    ("ERROR", "Ошибка"),
                ],
                default="INFO",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="evotorevent",
            name="sender",
            field=models.CharField(
                choices=[
                    ("INSTALLATION", "Установка / Удаление"),
                    ("STORE", "Магазин"),
                    ("TERMINAL", "Терминал"),
                    ("STAFF", "Персонал"),
                    ("GROUP", "Группа"),
                    ("PRODUCT", "Товар"),
                    ("ORDER", "Заказ"),
                    ("DOC", "Документы"),
                    ("MICS", "Неизвестно"),
                ],
                default="MICS",
                max_length=32,
            ),
        ),
    ]
