# Generated by Django 4.2.11 on 2024-06-10 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oscar.apps.catalogue.reviews.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.SmallIntegerField(
                        choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Оценка",
                    ),
                ),
                ("body", models.TextField(verbose_name="Текст отзыва")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Не просмотрен"),
                            (1, "Одобренный"),
                            (2, "Отклоненный"),
                        ],
                        default=oscar.apps.catalogue.reviews.utils.get_default_review_status,
                        verbose_name="Статус",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalogue.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв продукта",
                "verbose_name_plural": "Отзывы продуктов",
                "abstract": False,
                "unique_together": {("product", "user")},
            },
        ),
    ]
