# Generated by Django 4.2.11 on 2024-08-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_productreview_is_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="is_open",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Отзыв просмотрен"
            ),
        ),
    ]
