# Generated by Django 4.2.11 on 2024-04-01 08:39

from django.db import migrations, models
import django.db.models.deletion
import oscar.core.utils
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0027_attributeoption_code_attributeoptiongroup_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractAdditional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "slug",
                    oscar.models.fields.autoslugfield.AutoSlugField(
                        blank=True,
                        editable=False,
                        max_length=128,
                        populate_from="title",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "price_currency",
                    models.CharField(
                        default=oscar.core.utils.get_default_currency,
                        max_length=12,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price to sell.",
                        max_digits=12,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Old price.",
                        max_digits=12,
                        null=True,
                        verbose_name="Old Price",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Weight of additional product",
                        verbose_name="Weight",
                    ),
                ),
                (
                    "max_amount",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Max amount to one item",
                        verbose_name="Max amount",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Date updated"
                    ),
                ),
                (
                    "ranking",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Determines order of the products. A product with a higher value will appear before one with a lower ranking.",
                        verbose_name="Ranking",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="code",
            field=models.SlugField(max_length=128, verbose_name="Code"),
        ),
        migrations.CreateModel(
            name="Additional",
            fields=[
                (
                    "abstractadditional_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="catalogue.abstractadditional",
                    ),
                ),
            ],
            bases=("catalogue.abstractadditional",),
        ),
        migrations.AddField(
            model_name="product",
            name="product_additionals",
            field=models.ManyToManyField(
                blank=True,
                help_text="add product additional",
                to="catalogue.additional",
                verbose_name="Product additional",
            ),
        ),
    ]
