# Generated by Django 4.2.11 on 2024-11-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.IntegerField(
                blank=True,
                help_text="Вес товара в граммах.",
                null=True,
                verbose_name="Вес",
            ),
        ),
    ]
