# Generated by Django 4.2.11 on 2024-11-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_attribute_evotor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="evotor_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="ID Эвотор"
            ),
        ),
    ]
