# Generated by Django 4.2.11 on 2024-11-27 05:56

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_alter_product_evotor_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="additional",
            old_name="upc",
            new_name="article",
        ),
        migrations.RemoveField(
            model_name="product",
            name="upc",
        ),
        migrations.AddField(
            model_name="product",
            name="article",
            field=oscar.models.fields.NullCharField(
                help_text="Универсальный код товара (Артикул) является идентификатором для товара, который является специфичным для конкретного товара.",
                max_length=64,
                unique=True,
                verbose_name="Артикул товара",
            ),
        ),
    ]
