# Generated by Django 4.2.11 on 2024-11-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0005_rename_upc_additional_article_remove_product_upc_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="name",
        ),
    ]
