# Generated by Django 4.2.11 on 2024-12-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_rename_title_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attribute",
            name="evotor_id",
        ),
    ]
