# Generated by Django 4.2.11 on 2024-12-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0007_remove_attribute_evotor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="additional",
            name="evotor_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="ID Эвотор"
            ),
        ),
        migrations.AddField(
            model_name="additional",
            name="tax",
            field=models.CharField(
                choices=[
                    ("NO_VAT", "Без НДС."),
                    ("VAT_0", "Основная ставка 0%"),
                    ("VAT_10", "Основная ставка 10%."),
                    ("VAT_10_110", "Расчётная ставка 10%."),
                    (
                        "VAT_18",
                        "Основная ставка 18%. С первого января 2019 года может указывать как на 18%, так и на 20% ставку.",
                    ),
                    (
                        "VAT_18_118",
                        "Расчётная ставка 18%. С первого января 2019 года может указывать как на 18%, так и на 20% ставку.",
                    ),
                ],
                default="NO_VAT",
                max_length=128,
                verbose_name="Налог в процентах",
            ),
        ),
        migrations.AlterField(
            model_name="additional",
            name="is_public",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Показывать этот дополнительный товар у товаров.",
                verbose_name="Является общедоступным",
            ),
        ),
    ]
