# Generated by Django 4.2.11 on 2024-12-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_stockrecord_is_public"),
        ("catalogue", "0008_additional_evotor_id_additional_tax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="additional",
            name="stores",
            field=models.ManyToManyField(
                blank=True, to="store.store", verbose_name="Магазины"
            ),
        ),
    ]
