# Generated by Django 4.2.11 on 2024-12-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_stockrecord_is_public"),
        ("catalogue", "0010_additional_cost_price_alter_additional_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=128, verbose_name="Имя"),
                ),
                (
                    "evotor_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="ID Эвотор"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "stores",
                    models.ManyToManyField(
                        blank=True, to="store.store", verbose_name="Магазины"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория дополнительного товара",
                "verbose_name_plural": "Категории дополнительных товаров",
            },
        ),
    ]
