# Generated by Django 4.2.11 on 2024-12-11 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_stockrecord_is_public"),
        ("catalogue", "0011_additionalcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalcategory",
            name="stores",
        ),
        migrations.AddField(
            model_name="additionalcategory",
            name="store",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.store",
                verbose_name="Магазин",
            ),
            preserve_default=False,
        ),
    ]
