# Generated by Django 4.2.11 on 2024-12-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0012_remove_additionalcategory_stores_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additionalcategory",
            name="name",
        ),
    ]
