# Generated by Django 4.2.11 on 2024-12-12 06:58

from django.db import migrations
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0013_remove_additionalcategory_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="additional",
            name="code",
        ),
        migrations.RemoveField(
            model_name="category",
            name="code",
        ),
        migrations.AlterField(
            model_name="additional",
            name="article",
            field=oscar.models.fields.autoslugfield.AutoSlugField(
                allow_unicode=True,
                blank=True,
                default=1,
                editable=False,
                help_text="Универсальный код товара (Артикул) является идентификатором для товара, который является специфичным для конкретного товара.",
                max_length=64,
                overwrite=True,
                populate_from="name",
                unique=True,
                verbose_name="Артикул товара",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="article",
            field=oscar.models.fields.autoslugfield.AutoSlugField(
                allow_unicode=True,
                blank=True,
                default=1,
                editable=False,
                help_text="Универсальный код товара (Артикул) является идентификатором для товара, который является специфичным для конкретного товара.",
                max_length=64,
                overwrite=True,
                populate_from="name",
                verbose_name="Артикул товара",
            ),
            preserve_default=False,
        ),
    ]
