# Generated by Django 4.2.11 on 2024-12-12 07:00

from django.db import migrations
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0014_remove_additional_code_remove_category_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="article",
            field=oscar.models.fields.autoslugfield.AutoSlugField(
                allow_unicode=True,
                blank=True,
                editable=False,
                help_text="Универсальный код товара (Артикул) является идентификатором для товара, который является специфичным для конкретного товара.",
                max_length=64,
                overwrite=True,
                populate_from="slug",
                unique=True,
                verbose_name="Артикул товара",
            ),
        ),
    ]
