# Generated by Django 4.2.11 on 2024-12-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0016_alter_product_article"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdditionalCategory",
        ),
    ]
