# Generated by Django 4.2.11 on 2024-12-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0017_delete_additionalcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productclass",
            name="measure_name",
            field=models.CharField(
                choices=[
                    ("", "Не задано"),
                    ("шт", "шт - штуки"),
                    ("кг", "кг - килограммы"),
                    ("л", "л - литры"),
                    ("мл", "мл - миллилитры"),
                    ("м", "м - метры"),
                    ("компл", "компл - комплекты"),
                    ("упак", "упак - упаковки"),
                    ("ед", "ед - единицы"),
                ],
                default="",
                max_length=128,
                verbose_name="Единицы изменения",
            ),
        ),
    ]
