# Generated by Django 4.2.11 on 2024-11-26 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="store",
            options={
                "ordering": ("name", "code"),
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
            },
        ),
        migrations.AlterModelOptions(
            name="storeaddress",
            options={
                "verbose_name": "Адрес магазина",
                "verbose_name_plural": "Адреса магазинов",
            },
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stockrecords",
                to="store.store",
                verbose_name="Магазин",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Магазин доступен для клиентов?",
                verbose_name="Активен",
            ),
        ),
        migrations.AlterField(
            model_name="storeaddress",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="store.store",
                verbose_name="Магазин",
            ),
        ),
    ]
