# Generated by Django 4.2.11 on 2024-11-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_store_options_alter_storeaddress_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockrecord",
            name="evotor_code",
            field=models.CharField(
                blank=True,
                help_text="Эвотор код, для связи товара и товарной записи",
                max_length=25,
                verbose_name="Эвотор Code",
            ),
        ),
    ]
