# Generated by Django 4.2.11 on 2024-12-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_stockrecord_evotor_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockrecord",
            name="is_public",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Товар доступен к покупке",
                verbose_name="Доступен",
            ),
        ),
    ]
