# Generated by Django 4.2.11 on 2024-12-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="refundable",
            field=models.BooleanField(blank=True, verbose_name="Возврат возможен?"),
        ),
    ]
