# Generated by Django 4.2.11 on 2024-11-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("new-order", "Уведомление о новом заказе"),
                            ("status-order", "Уведомление об изменении статуса заказа"),
                            ("technical", "Техническое уведомление"),
                            ("offer", "Уведомление о персональном предложении"),
                            ("misc", "Без типа"),
                        ],
                        default="misc",
                        max_length=128,
                        verbose_name="Тип сообщения",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "date_sent",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение Телеграм",
                "verbose_name_plural": "Сообщения Телеграм",
                "ordering": ["type"],
            },
        ),
    ]
