# Generated by Django 4.2.11 on 2024-09-17 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegrammassage",
            options={
                "ordering": ["type"],
                "verbose_name": "Сообщение Телеграм",
                "verbose_name_plural": "Сообщения Телеграм",
            },
        ),
        migrations.RenameField(
            model_name="telegrammassage",
            old_name="description",
            new_name="massage",
        ),
        migrations.RemoveField(
            model_name="telegrammassage",
            name="code",
        ),
        migrations.RemoveField(
            model_name="telegrammassage",
            name="name",
        ),
        migrations.AddField(
            model_name="telegrammassage",
            name="type",
            field=models.CharField(
                default=1, max_length=128, verbose_name="Тип сообщения"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="telegrammassage",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
    ]
