# Generated by Django 4.2.11 on 2024-09-18 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telegram", "0002_alter_telegrammassage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(max_length=128, verbose_name="Тип сообщения"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Информация"),
                            ("warning", "Предупреждение"),
                            ("error", "Ошибка"),
                        ],
                        default="info",
                        max_length=128,
                        verbose_name="Тип сообщения",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонал подписанный на Телеграм",
                "verbose_name_plural": "Персонал подписанный на Телеграм",
                "ordering": ["user"],
                "abstract": False,
            },
        ),
    ]
