# Generated by Django 4.2.11 on 2024-09-20 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telegram", "0003_telegramstaff"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(max_length=128, verbose_name="ID Телеграм чата"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Показывать эту категорию в результатах поиска и каталогах.",
                        verbose_name="Является сотрудником",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Информация"),
                            ("warning", "Предупреждение"),
                            ("error", "Ошибка"),
                        ],
                        default="info",
                        max_length=128,
                        verbose_name="Тип сообщения",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь Сайта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Персонал подписанный на Телеграм",
                "verbose_name_plural": "Персонал подписанный на Телеграм",
                "ordering": ["user"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="telegrammassage",
            name="date_sent",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата отправки",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="TelegramStaff",
        ),
    ]
