# Generated by Django 4.2.11 on 2024-09-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0004_telegramuser_telegrammassage_date_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Активен ли пользователь? Определяет доступна ли рассылка сообщений",
                verbose_name="Активен",
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="type",
            field=models.CharField(
                choices=[
                    ("info", "Информация"),
                    ("warning", "Предупреждение"),
                    ("error", "Ошибка"),
                    ("off", "Отключить"),
                ],
                default="info",
                max_length=128,
                verbose_name="Тип сообщения",
            ),
        ),
    ]
