# Generated by Django 4.2.11 on 2024-09-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0005_telegramuser_is_active_alter_telegramuser_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="is_staff",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Показывать эту категорию в результатах поиска и каталогах.",
                verbose_name="Является сотрудником",
            ),
        ),
    ]
