# Generated by Django 4.2.11 on 2024-09-23 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0006_alter_telegramuser_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegrammassage",
            name="user",
        ),
        migrations.AddField(
            model_name="telegrammassage",
            name="tg_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="telegram.telegramuser",
                verbose_name="Пользователь Телеграм",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="telegrammassage",
            name="type",
            field=models.CharField(
                choices=[
                    ("new-order", " Только уведомления о новых заказах"),
                    (
                        "status-order",
                        "Уведомления об изменении заказов и новых заказах",
                    ),
                    ("technical", "Технические уведомления"),
                    ("misc", "Без типа"),
                ],
                max_length=128,
                verbose_name="Тип сообщения",
            ),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="type",
            field=models.CharField(
                choices=[
                    ("new-order", " Только уведомления о новых заказах"),
                    (
                        "status-order",
                        "Уведомления об изменении заказов и новых заказах",
                    ),
                    ("technical", "Технические уведомления"),
                    ("off", "Отключить уведомления"),
                ],
                default="new-order",
                max_length=128,
                verbose_name="Тип сообщения",
            ),
        ),
    ]
