# Generated by Django 4.2.11 on 2024-09-23 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "telegram",
            "0007_remove_telegrammassage_user_telegrammassage_tg_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegrammassage",
            name="tg_user",
        ),
        migrations.AddField(
            model_name="telegrammassage",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь Сайта",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="TelegramUser",
        ),
    ]
