# Generated by Django 4.2.11 on 2024-09-24 10:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telegram", "0009_alter_telegrammassage_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TelegramMassage",
            new_name="TelegramMessage",
        ),
    ]
