# Generated by Django 4.2.11 on 2024-12-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMBulk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evotor_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="ID Эвотор"
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("product", "Товары или доп. товары"),
                            ("product-group", "Категории"),
                        ],
                        default="product",
                        max_length=128,
                        verbose_name="Тип объектов",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Задача принята в работу"),
                            ("RUNNING", "Задача обрабатывается"),
                            ("COMPLETED", "Обработка задачи завершена"),
                            ("DECLINED", "Задача отклонена"),
                            ("FAILED", "Обработать задачу не удалось"),
                        ],
                        default="ACCEPTED",
                        max_length=128,
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Массовая задача Эвотор",
                "verbose_name_plural": "Массовая задача Эвотор",
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="CRMMobileCashierToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Токен пользователя мобильного кассира Эвотор",
                "verbose_name_plural": "Токены пользователя мобильного кассира Эвотор",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="crmevent",
            options={
                "ordering": ("-date_created",),
                "verbose_name": "Событие Эвотор",
                "verbose_name_plural": "События Эвотор",
            },
        ),
        migrations.RemoveField(
            model_name="crmevent",
            name="type",
        ),
        migrations.AddField(
            model_name="crmevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATION", "Создание"),
                    ("DELETE", "Удаление"),
                    ("UPDATE", "Обновление"),
                    ("INFO", "Инфо"),
                    ("BULK", "Переодическая задача"),
                    ("ERROR", "Ошибка"),
                ],
                default="INFO",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="crmevent",
            name="sender",
            field=models.CharField(
                choices=[
                    ("TERMINAL", "Терминал"),
                    ("STORE", "Магазин"),
                    ("ORDER", "Заказ"),
                    ("DOC", "Документы"),
                    ("INSTALLATION", "Установка / Удаление"),
                    ("STAFF", "Персонал"),
                    ("PRODUCT", "Товар"),
                    ("GROUP", "Группа"),
                    ("MICS", "Неизвестно"),
                ],
                default="MICS",
                max_length=32,
            ),
        ),
    ]
