# Generated by Django 4.2.11 on 2024-11-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmevent",
            name="sender",
            field=models.CharField(
                choices=[
                    ("TERMINAL", "Терминал"),
                    ("STORE", "Магазин"),
                    ("RECEIPT", "Чек"),
                    ("DOC", "Документы"),
                    ("INSTALLATION", "Установка / Удаление"),
                    ("STAFF", "Персонал"),
                    ("PRODUCT", "товары"),
                    ("MICS", "Неизвестно"),
                ],
                default="MICS",
                max_length=32,
            ),
        ),
    ]
