# Generated by Django 4.2.11 on 2024-12-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_crmevent_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmevent",
            name="sender",
            field=models.CharField(
                choices=[
                    ("TERMINAL", "Терминал"),
                    ("STORE", "Магазин"),
                    ("ORDER", "Заказ"),
                    ("DOC", "Документы"),
                    ("INSTALLATION", "Установка / Удаление"),
                    ("STAFF", "Персонал"),
                    ("PRODUCT", "Товар"),
                    ("MICS", "Неизвестно"),
                ],
                default="MICS",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="crmevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREATION", "Создание"),
                    ("DELETE", "Удаление"),
                    ("UPDATE", "Обновление"),
                    ("INFO", "Инфо"),
                    ("ERROR", "Ошибка"),
                ],
                default="INFO",
                max_length=255,
            ),
        ),
    ]
