# Generated by Django 4.2.11 on 2024-12-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_crmevent_sender_alter_crmevent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmevent",
            name="sender",
            field=models.CharField(
                choices=[
                    ("TERMINAL", "Терминал"),
                    ("STORE", "Магазин"),
                    ("ORDER", "Заказ"),
                    ("DOC", "Документы"),
                    ("INSTALLATION", "Установка / Удаление"),
                    ("STAFF", "Персонал"),
                    ("PRODUCT", "Товар"),
                    ("GROUP", "Группа"),
                    ("MICS", "Неизвестно"),
                ],
                default="MICS",
                max_length=32,
            ),
        ),
    ]
