# Generated by Django 4.2.11 on 2024-12-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_crmevent_sender"),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMBulk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evotor_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="ID Эвотор"
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("product", "Товары или доп. товары"),
                            ("product-group", "Категории"),
                        ],
                        default="product",
                        max_length=128,
                        verbose_name="Тип объектов",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Задача принята в работу"),
                            ("RUNNING", "Задача обрабатывается"),
                            ("COMPLETED", "Обработка задачи завершена"),
                            ("DECLINED", "Задача отклонена"),
                            ("FAILED", "Обработать задачу не удалось"),
                        ],
                        default="ACCEPTED",
                        max_length=128,
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Массовая задача Эвотор",
                "verbose_name_plural": "Массовая задача Эвотор",
                "ordering": ("-date_created",),
            },
        ),
        migrations.AlterModelOptions(
            name="crmevent",
            options={
                "ordering": ("-date_created",),
                "verbose_name": "Событие Эвотор",
                "verbose_name_plural": "События Эвотор",
            },
        ),
        migrations.RemoveField(
            model_name="crmevent",
            name="type",
        ),
        migrations.AddField(
            model_name="crmevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CREATION", "Создание"),
                    ("DELETE", "Удаление"),
                    ("UPDATE", "Обновление"),
                    ("INFO", "Инфо"),
                    ("BULK", "Переодическая задача"),
                    ("ERROR", "Ошибка"),
                ],
                default="INFO",
                max_length=255,
            ),
        ),
    ]
