# Generated by Django 4.2.11 on 2024-12-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_crmbulk_alter_crmevent_options_remove_crmevent_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CRMMobileCashierToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Токен пользователя мобильного кассира Эвотор",
                "verbose_name_plural": "Токены пользователя мобильного кассира Эвотор",
                "ordering": ("-created_at",),
            },
        ),
    ]
