# Generated by Django 4.2.11 on 2025-03-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="store_default",
            field=models.ForeignKey(
                blank=True,
                help_text="Данный магазин используется, если клиент еще не выбрал магазин",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.store",
                verbose_name="Основной магазин",
            ),
        ),
    ]
