# Generated by Django 4.2.11 on 2025-03-20 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], verbose_name='Оценка')),
                ('body', models.TextField(verbose_name='Текст отзыва')),
                ('status', models.SmallIntegerField(choices=[(0, 'Неизвестно'), (1, 'Полезный'), (2, 'Неполезный')], default=0, verbose_name='Статус')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(db_index=True, default=False, verbose_name='Отзыв просмотрен')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв на заказ',
                'verbose_name_plural': 'Отзывы на заказы',
                'unique_together': {('order', 'user')},
            },
        ),
    ]
