# Generated by Django 4.2.11 on 2025-03-19 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0014_delete_groupevotor"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvotorBulk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evotor_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="ID Эвотор"
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("product", "Товары или доп. товары"),
                            ("product-group", "Категории"),
                        ],
                        default="product",
                        max_length=128,
                        verbose_name="Тип объектов",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Задача принята в работу"),
                            ("RUNNING", "Задача обрабатывается"),
                            ("COMPLETED", "Обработка задачи завершена"),
                            ("DECLINED", "Задача отклонена"),
                            ("FAILED", "Обработать задачу не удалось"),
                        ],
                        default="ACCEPTED",
                        max_length=128,
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "date_finish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Массовая задача Эвотор",
                "verbose_name_plural": "Массовая задача Эвотор",
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="EvotorEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("INSTALLATION", "Установка / Удаление"),
                            ("STORE", "Магазин"),
                            ("TERMINAL", "Терминал"),
                            ("STAFF", "Персонал"),
                            ("GROUP", "Группа"),
                            ("PRODUCT", "Товар"),
                            ("ORDER", "Заказ"),
                            ("DOC", "Документы"),
                            ("MICS", "Неизвестно"),
                        ],
                        default="MICS",
                        max_length=32,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATION", "Создание"),
                            ("DELETE", "Удаление"),
                            ("UPDATE", "Обновление"),
                            ("INFO", "Инфо"),
                            ("BULK", "Переодическая задача"),
                            ("ERROR", "Ошибка"),
                        ],
                        default="INFO",
                        max_length=32,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие Эвотор",
                "verbose_name_plural": "События Эвотор",
                "ordering": ("-date_created",),
            },
        ),
        migrations.CreateModel(
            name="UserGroupEvotor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evotor_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evotor",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа пользователей Эвотор",
                "verbose_name_plural": "Группа пользователей Эвотор",
                "unique_together": {("group", "evotor_id")},
            },
        ),
    ]
