# Generated by Django 4.2.11 on 2024-06-10 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalogue", "0001_initial"),
        ("basket", "0001_initial"),
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineattribute",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalogue.option",
                verbose_name="Опция",
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="basket.basket",
                verbose_name="Корзина",
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket_lines",
                to="catalogue.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="stockrecord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket_lines",
                to="partner.stockrecord",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baskets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
