# Generated by Django 4.2.11 on 2024-08-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("basket", "0002_initial"),
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="stockrecord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket_lines",
                to="partner.stockrecord",
            ),
        ),
    ]
