# Generated by Django 4.2.11 on 2024-09-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0005_basket_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Открыто - сейчас активна"),
                    ("Merged", "Объединено – заменено другой корзиной"),
                    (
                        "Saved",
                        "Сохранено - можно будет заказать позже или в другой точке продажи",
                    ),
                    ("Frozen", "Заморожено – корзину нельзя изменить"),
                    ("Submitted", "Потдвержено - заказано"),
                ],
                default="Open",
                max_length=128,
                verbose_name="Статус",
            ),
        ),
    ]
