# Generated by Django 4.2.11 on 2024-09-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0006_alter_basket_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="tax_code",
        ),
        migrations.AlterField(
            model_name="basket",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Открыто - сейчас активна"),
                    ("Merged", "Объединено – заменено другой корзиной"),
                    ("Frozen", "Заморожено – корзину нельзя изменить"),
                    ("Submitted", "Потдвержено - заказано"),
                ],
                default="Open",
                max_length=128,
                verbose_name="Статус",
            ),
        ),
    ]
