# Generated by Django 4.2.11 on 2024-09-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0007_remove_line_tax_code_alter_basket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="tax_code",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Налоговый код"
            ),
        ),
    ]
