# Generated by Django 4.2.11 on 2024-10-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0008_line_tax_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="line",
            name="price",
        ),
    ]
